angular.module("randominion").controller("cardBrowserController", ["$scope", "$routeParams", function($scope, $routeParams) {

    $scope.cardView = $routeParams.viewState;
    $scope.page = $routeParams.cardSet;

    $scope.cards = {
        base: [
            {
                cost: 6,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Adventurer",
                imgUrl: "images/Base/adventurer.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Base",
                name: "Bureaucrat",
                imgUrl: "images/Base/bureaucrat.jpg"
            },
            {
                cost: 2,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Cellar",
                imgUrl: "images/Base/cellar.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Chancellor",
                imgUrl: "images/Base/chancellor.jpg"
            },
            {
                cost: 2,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Base",
                name: "Chapel",
                imgUrl: "images/Base/chapel.jpg"
            },
            {
                cost: 5,
                plusCards: 4,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Council Room",
                imgUrl: "images/Base/councilroom.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Base",
                name: "Feast",
                imgUrl: "images/Base/feast.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 2,
                plusBuys: 1,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Festival",
                imgUrl: "images/Base/festival.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAction: false,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                isVictory: true,
                type: "Victory",
                set: "Base",
                name: "Gardens",
                imgUrl: "images/Base/gardens.jpg"
            },
            {
                cost: 5,
                plusCards: 2,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Laboratory",
                imgUrl: "images/Base/laboratory.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Library",
                imgUrl: "images/Base/library.jpg"
            },
            {
                cost: 5,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 1,
                plusGold: 1,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Market",
                imgUrl: "images/Base/market.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Militia",
                imgUrl: "images/Base/militia.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Base",
                name: "Mine",
                imgUrl: "images/Base/mine.jpg"
            },
            {
                cost: 2,
                plusCards: 2,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: false,
                type: "Action- Defense",
                set: "Base",
                name: "Moat",
                imgUrl: "images/Base/moat.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Base",
                name: "Moneylender",
                imgUrl: "images/Base/moneylender.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Base",
                name: "Remodel",
                imgUrl: "images/Base/remodel.jpg"
            },
            {
                cost: 4,
                plusCards: 3,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Smithy",
                imgUrl: "images/Base/smithy.jpg"
            },
            {
                cost: 4,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Base",
                name: "Spy",
                imgUrl: "images/Base/spy.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Base",
                name: "Thief",
                imgUrl: "images/Base/thief.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Throne Room",
                imgUrl: "images/Base/throneroom.jpg"
            },
            {
                cost: 3,
                plusCards: 1,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Village",
                imgUrl: "images/Base/village.jpg"
            },
            {
                cost: 5,
                plusCards: 2,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Base",
                name: "Witch",
                imgUrl: "images/Base/witch.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Woodcutter",
                imgUrl: "images/Base/woodcutter.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Base",
                name: "Workshop",
                imgUrl: "images/Base/workshop.jpg"
            }
        ],
        alchemy : [
            {
                cost: 3,
                potionCost: 1,
                plusCards: 2,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Alchemy",
                name: "Alchemist",
                imgUrl: "images/Alchemy/alchemist.jpg"
            },
            {
                cost: 2,
                potionCost: 1,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Alchemy",
                name: "Apothecary",
                imgUrl: "images/Alchemy/apothecary.jpg"
            },
            {
                cost: 5,
                potionCost: 0,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Alchemy",
                name: "Apprentice",
                imgUrl: "images/Alchemy/apprentice.jpg"
            },
            {
                cost: 3,
                potionCost: 1,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Alchemy",
                name: "Familiar",
                imgUrl: "images/Alchemy/familiar.jpg"
            },
            {
                cost: 4,
                potionCost: 1,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Alchemy",
                name: "Golem",
                imgUrl: "images/Alchemy/golem.jpg"
            },
            {
                cost: 2,
                potionCost: 0,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 1,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Alchemy",
                name: "Herbalist",
                imgUrl: "images/Alchemy/herbalist.jpg"
            },
            {
                cost: 4,
                potionCost: 1,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                isTreasure: true,
                type: "Treasure",
                set: "Alchemy",
                name: "Philosopher's Stone",
                imgUrl: "images/Alchemy/philosophersstone.jpg"
            },
            {
                cost: 6,
                potionCost: 1,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Alchemy",
                name: "Possession",
                imgUrl: "images/Alchemy/possession.jpg"
            },
            {
                cost: 2,
                potionCost: 1,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Alchemy",
                name: "Scrying Pool",
                imgUrl: "images/Alchemy/scryingpool.jpg"
            },
            {
                cost: 0,
                potionCost: 1,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Alchemy",
                name: "Transmute",
                imgUrl: "images/Alchemy/transmute.jpg"
            },
            {
                cost: 2,
                potionCost: 1,
                plusCards: 0,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Alchemy",
                name: "University",
                imgUrl: "images/Alchemy/university.jpg"
            },
            {
                cost: 0,
                potionCost: 1,
                plusCards: 0,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                isVictory: true,
                type: "Victory",
                set: "Alchemy",
                name: "Vineyard",
                imgUrl: "images/Alchemy/vineyard.jpg"
            }
        ],
        intrigue : [
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Baron",
                imgUrl: "images/Intrigue/baron.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 1,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Bridge",
                imgUrl: "images/Intrigue/bridge.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Conspirator",
                imgUrl: "images/Intrigue/conspirator.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Coppersmith",
                imgUrl: "images/Intrigue/coppersmith.jpg"
            },
            {
                cost: 2,
                plusCards: 3,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Courtyard",
                imgUrl: "images/Intrigue/courtyard.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                isVictory: true,
                type: "Victory",
                set: "Intrigue",
                name: "Duke",
                imgUrl: "images/Intrigue/duke.jpg"
            },
            {
                cost: 3,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                isVictory: true,
                type: "Action- Victory",
                set: "Intrigue",
                name: "Great Hall",
                imgUrl: "images/Intrigue/greathall.jpg"
            },
            {
                cost: 6,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                isVictory: true,
                type: "Treasure- Victory",
                set: "Intrigue",
                name: "Harem",
                imgUrl: "images/Intrigue/harem.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Ironworks",
                imgUrl: "images/Intrigue/ironworks.jpg"
            },
            {
                cost: 3,
                plusCards: 2,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Intrigue",
                name: "Masquerade",
                imgUrl: "images/Intrigue/masquerade.jpg"
            },
            {
                cost: 4,
                plusCards: 1,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Mining Village",
                imgUrl: "images/Intrigue/miningvillage.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Intrigue",
                name: "Minion",
                imgUrl: "images/Intrigue/minion.jpg"
            },
            {
                cost: 6,
                plusCards: 3,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                isVictory: true,
                type: "Action- Victory",
                set: "Intrigue",
                name: "Nobles",
                imgUrl: "images/Intrigue/nobles.jpg"
            },
            {
                cost: 2,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 1,
                plusGold: 1,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Pawn",
                imgUrl: "images/Intrigue/pawn.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: true,
                type: "Action- True",
                set: "Intrigue",
                name: "Saboteur",
                imgUrl: "images/Intrigue/saboteur.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Scout",
                imgUrl: "images/Intrigue/scout.jpg"
            },
            {
                cost: 2,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: false,
                type: "Action- Defense",
                set: "Intrigue",
                name: "Secret Chamber",
                imgUrl: "images/Intrigue/secretchamber.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Shanty Town",
                imgUrl: "images/Intrigue/shantytown.jpg"
            },
            {
                cost: 3,
                plusCards: 2,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: true,
                allowTrashes: true,
                type: "Action",
                set: "Intrigue",
                name: "Steward",
                imgUrl: "images/Intrigue/steward.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: true,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Intrigue",
                name: "Swindler",
                imgUrl: "images/Intrigue/swindler.jpg"
            },
            {
                cost: 5,
                plusCards: 3,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Intrigue",
                name: "Torturer",
                imgUrl: "images/Intrigue/torturer.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: true,
                type: "Action",
                set: "Intrigue",
                name: "Trading Post",
                imgUrl: "images/Intrigue/tradingpost.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: false,
                type: "Action",
                set: "Intrigue",
                name: "Tribute",
                imgUrl: "images/Intrigue/tribute.jpg"
            },
            {
                cost: 5,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: true,
                type: "Action",
                set: "Intrigue",
                name: "Upgrade",
                imgUrl: "images/Intrigue/upgrade.jpg"
            },
            {
                cost: 3,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: true,
                type: "Action",
                set: "Intrigue",
                name: "Wishing Well",
                imgUrl: "images/Intrigue/wishingwell.jpg"
            }
        ],
        seaside : [
            {
                cost: 3,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Seaside",
                name: "Ambassador",
                imgUrl: "images/seaside/ambassador.jpg"
            },
            {
                cost: 5,
                plusCards: 1,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 1,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Bazaar",
                imgUrl: "images/seaside/bazaar.jpg"
            },
            {
                cost: 4,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Duration",
                set: "Seaside",
                name: "Caravan",
                imgUrl: "images/seaside/caravan.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Seaside",
                name: "Cutpurse",
                imgUrl: "images/seaside/cutpurse.jpg"
            },
            {
                cost: 2,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Embargo",
                imgUrl: "images/seaside/embargo.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Explorer",
                imgUrl: "images/seaside/explorer.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 1,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Duration",
                set: "Seaside",
                name: "Fishing Village",
                imgUrl: "images/seaside/fishingvillage.jpg"
            },
            {
                cost: 5,
                plusCards: 2,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Seaside",
                name: "Ghost Ship",
                imgUrl: "images/seaside/ghostship.jpg"
            },
            {
                cost: 2,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Duration",
                set: "Seaside",
                name: "Haven",
                imgUrl: "images/seaside/haven.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Victory",
                set: "Seaside",
                name: "Island",
                imgUrl: "images/seaside/island.jpg"
            },
            {
                cost: 2,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: true,
                allowTrashes: false,
                type: "Action- Duration",
                set: "Seaside",
                name: "Lighthouse",
                imgUrl: "images/seaside/lighthouse.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Lookout",
                imgUrl: "images/seaside/lookout.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Duration",
                set: "Seaside",
                name: "Merchant Ship",
                imgUrl: "images/seaside/merchantship.jpg"
            },
            {
                cost: 2,
                plusCards: 0,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Native Village",
                imgUrl: "images/seaside/nativevillage.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Navigator",
                imgUrl: "images/seaside/navigator.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Duration",
                set: "Seaside",
                name: "Outpost",
                imgUrl: "images/seaside/outpost.jpg"
            },
            {
                cost: 2,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Pearl Diver",
                imgUrl: "images/seaside/pearldiver.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Seaside",
                name: "Pirate Ship",
                imgUrl: "images/seaside/pirateship.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Seaside",
                name: "Salvager",
                imgUrl: "images/seaside/salvager.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Seaside",
                name: "Seahag",
                imgUrl: "images/seaside/seahag.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Smugglers",
                imgUrl: "images/seaside/smugglers.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Duration",
                set: "Seaside",
                name: "Tactician",
                imgUrl: "images/seaside/tactician.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Treasure Map",
                imgUrl: "images/seaside/treasuremap.jpg"
            },
            {
                cost: 4,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 1,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Treasury",
                imgUrl: "images/seaside/treasury.jpg"
            },
            {
                cost: 3,
                plusCards: 3,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Seaside",
                name: "Warehouse",
                imgUrl: "images/seaside/warehouse.jpg"
            },
            {
                cost: 5,
                plusCards: 2,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Duration",
                set: "Seaside",
                name: "Wharf",
                imgUrl: "images/seaside/wharf.jpg"
            }
        ],
        promo : [
            {
                cost: 3,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Promo",
                name: "Black Market",
                imgUrl: "images/promo/blackmarket.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Promo",
                name: "Envoy",
                imgUrl: "images/promo/envoy.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Promo",
                name: "Governor",
                imgUrl: "images/promo/governor.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Treasure",
                set: "Promo",
                name: "Stash",
                imgUrl: "images/promo/stash.jpg"
            },
            {
                cost: 4,
                plusCards: 1,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Promo",
                name: "Walled Village",
                imgUrl: "images/promo/walledvillage.jpg"
            }
        ],
        cornucopia: [
            {
                cost: 0,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                notInSupply: true,
                type: "Action- Prize",
                set: "Cornucopia",
                name: "Bag of Gold",
                imgUrl: "images/cornucopia/bagofgold.jpg"
            },
            {
                cost: 0,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                notInSupply: true,
                type: "Treasure- Prize",
                set: "Cornucopia",
                name: "Diadem",
                imgUrl: "images/cornucopia/diadem.jpg"
            },
            {
                cost: 6,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Victory",
                set: "Cornucopia",
                name: "Fairgrounds",
                imgUrl: "images/cornucopia/fairgrounds.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 2,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Cornucopia",
                name: "Farming Village",
                imgUrl: "images/cornucopia/farmingvillage.jpg"
            },
            {
                cost: 0,
                plusCards: 2,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                notInSupply: true,
                type: "Action- Attack- Prize",
                set: "Cornucopia",
                name: "Followers",
                imgUrl: "images/cornucopia/followers.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Cornucopia",
                name: "Fortune Teller",
                imgUrl: "images/cornucopia/fortuneteller.jpg"
            },
            {
                cost: 2,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 2,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Cornucopia",
                name: "Hamlet",
                imgUrl: "images/cornucopia/hamlet.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Cornucopia",
                name: "Harvest",
                imgUrl: "images/cornucopia/harvest.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Treasure",
                set: "Cornucopia",
                name: "Horn of Plenty",
                imgUrl: "images/cornucopia/hornofplenty.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 3,
                isAttack: false,
                isReact: true,
                allowTrashes: false,
                type: "Action- Defense",
                set: "Cornucopia",
                name: "Horse Traders",
                imgUrl: "images/cornucopia/horsetraders.jpg"
            },
            {
                cost: 5,
                plusCards: 1,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Cornucopia",
                name: "Hunting Party",
                imgUrl: "images/cornucopia/huntingparty.jpg"
            },
            {
                cost: 5,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 2,
                isAttack: true,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Cornucopia",
                name: "Jester",
                imgUrl: "images/cornucopia/jester.jpg"
            },
            {
                cost: 3,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Cornucopia",
                name: "Menagerie",
                imgUrl: "images/cornucopia/menagerie.jpg"
            },
            {
                cost: 0,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                notInSupply: true,
                type: "Action- Prize",
                set: "Cornucopia",
                name: "Princess",
                imgUrl: "images/cornucopia/princess.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 0,
                plusBuys: 1,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: true,
                type: "Action",
                set: "Cornucopia",
                name: "Remake",
                imgUrl: "images/cornucopia/remake.jpg"
            },
            {
                cost: 4,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action",
                set: "Cornucopia",
                name: "Tournament",
                imgUrl: "images/cornucopia/tournament.jpg"
            },
            {
                cost: 0,
                plusCards: 0,
                plusActions: 1,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                notInSupply: true,
                type: "Action- Prize",
                set: "Cornucopia",
                name: "Trusty Steed",
                imgUrl: "images/cornucopia/trustysteed.jpg"
            },
            {
                cost: 4,
                plusCards: 2,
                plusActions: 0,
                plusBuys: 0,
                plusGold: 0,
                isAttack: false,
                isReact: false,
                allowTrashes: false,
                type: "Action- Attack",
                set: "Cornucopia",
                name: "Young Witch",
                imgUrl: "images/cornucopia/youngwitch.jpg"
            }
        ]

    };

} ]);